### ISSUE TITLE
Fill data attribute dynamically

### ISSUE THREAD

**Issue by believelody** [SuperiorJT/angular2-qrcode#10]
Hello sir,

Newbie in angular, I've just used your angular2-qrcode. I would like to fill data attribute dynamically by passing a variable which contains string I want to code. How can I do this?
I've tried something like this:
  ```
<ion-item>
    <ion-label>Entrez votre texte</ion-label>
    <ion-input type="text" [(ngModel)]="textField"></ion-input>
  </ion-item>
  <button ion-button block (click)="click()">Scan</button>
  <button ion-button block (click)="make()">Make</button>
  <p>{{textEncode}}</p>
  <div>
    <qr-code [data]="'{{textEncode}}'" [size]="250" [type]="8"></qr-code>
  </div>
```

and in my typescript file it's like:
export class HomePage {
  private textField: any;
  private textEncode: any;

  constructor(public navCtrl: NavController) {
    this.textField = '';
    this.textEncode = '';
  }

  // For reading barcode, work properly
  click() {
    BarcodeScanner.scan().then((barcodeData) => {
      alert("Text: " + barcodeData.text + "\n" + "Format: " + barcodeData.format);
    }, (err) => {
      alert(err.message);
    });
  }

  // For generating qr code, when I click on it, it display qr code then my app crashes
  make() {
    this.textEncode = this.textField;
  }
}

When I execute I have the white screen death. Or, when I remove the qrcode tag, the p tag works correctly.

Thanks for your help, I work on ionic 2.

**Comment by SuperiorJT** [comment]
I think the problem here is the way you are trying to send the barcode data to the qr-code component:

```
<qr-code [data]="'{{textEncode}}'" [size]="250" [type]="8"></qr-code>
```

In Angular 2, you should send the data attribute using just the variable name, making sure that it is a field of the parent component.

Ex:
```
<qr-code [data]="textEncode" [size]="250" [type]="8"></qr-code>
```

Try removing the surrounding curly brackets and see what results you get.

**Comment by SuperiorJT** [comment]
Closing this since nobody else seems to be having issues with it.
