### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ruudboon** [SuperiorJT/angular2-qrcode#11]
Could you add a parameter to style the colors of the QR?

Thnx

**Comment by SuperiorJT** [comment]
There isn't a way for me to do that unless I write my own generator. Unfortunately, I don't have the time to do that; but as an alternative, you may want to try using CSS filters on the image itself.

[Here is a link for info on CSS filters.](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)

**Comment by ruudboon** [comment]
Thnx @SuperiorJT I will look into it, or switch to a different lib.
