### ISSUE TITLE
ionic build android --prod error

### ISSUE THREAD

**Issue by merlinyang521** [SuperiorJT/angular2-qrcode#13]
onic build android --prod
[15:04:54]  build prod failed: Unexpected value 'QRCodeModule' imported by the module 'AppModule'
[15:04:54]  ionic-app-script task: "build"
[15:04:54]  Error: Unexpected value 'QRCodeModule' imported by the module 'AppModule'
Error: Unexpected value 'QRCodeModule' imported by the module 'AppModule'
    at /private/var/www/app/mo/node_modules/@angular/compiler/bundles/compiler.umd.js:14675:3

**Comment by cedWetzel** [comment]
I have the same issue here. I have tried #9 but it didn't help in any way.

**Comment by vinlim** [comment]
The issue persist, without ability to build android.

**Comment by ramzed** [comment]
Same problem.
I also have tried https://github.com/SuperiorJT/angular2-qrcode/pull/9 but it didn't help.

**Comment by ramzed** [comment]
Hello,
Is any solution for this problem?

**Comment by ruudboon** [comment]
Same issue here. Only when creating production build works using serve. 
```
ng build --prod
```

**Comment by ramzed** [comment]
I resolved problem. I will write my solution later

**Comment by ramzed** [comment]
Sorry, I should to clone repo and create merge request. But I didn't have enough time to get a good deal in the existing code to make a request.

1. First, I removed angular2-qrcode. And installed qrious and canvas via npm:
```bash
npm remove angular2-qrcode --save
npm install canvas --save
npm install qrious --save
```

2. I created new file `/src/mycustom-components/angular2-qrcode/angular2-qrcode.component.ts`
```javascript
import { Component, ElementRef, OnChanges, Input } from '@angular/core';
import QRious from 'qrious';

@Component({
  selector: 'qr-code',
  template: `
      <div></div>
  `
})
export class QRCodeComponent implements OnChanges {

    private elementRef;
    @Input() value: string;
    @Input() size: number;
    background: string;
    backgroundAlpha: number;
    foreground: string;
    foregroundAlpha: number;
    level: string;
    mime: string;
    padding: number;
    canvas: boolean;

    constructor(public el: ElementRef) {
      this.elementRef = el;
      this.background = 'white';
      this.backgroundAlpha = 1.0;
      this.foreground = 'black';
      this.foregroundAlpha = 1.0;
      this.level = 'L';
      this.mime = 'image/png';
      this.padding = null;
      this.size = 300;
      this.value = 'uid';
      this.canvas = false;
    };

    ngOnChanges(changes) {
      if ('background' in changes ||
        'backgroundAlpha' in changes ||
        'foreground' in changes ||
        'foregroundAlpha' in changes ||
        'level' in changes ||
        'mime' in changes ||
        'padding' in changes ||
        'size' in changes ||
        'value' in changes ||
        'canvas' in changes) {
            this.generate();
          }
    }

    generate() {
        try {
            var el = this.elementRef.nativeElement;
            el.innerHTML = '';
            var qr = new QRious({
                background: this.background,
                backgroundAlpha: this.backgroundAlpha,
                foreground: this.foreground,
                foregroundAlpha: this.foregroundAlpha,
                level: this.level,
                mime: this.mime,
                padding: this.padding,
                size: this.size,
                value: this.value
            });
            if (this.canvas) {
                el.appendChild(qr.canvas);
            }
            else {
                el.appendChild(qr.image);
            }
        }
        catch (e) {
            console.error("Could not generate QR Code: " + e.message);
        }
    }


}
```

3. Also we need to create `/src/mycustom-components/angular2-qrcode/angular2-qrcode.component.scss`
```scss
qr-code {
}

```

4. Then need import **QRCodeComponent** in `/src/app/app.module.ts`
```javascript
...
import { QRCodeComponent } from '../mycustom-components/angular2-qrcode';
...
@NgModule({
  declarations: [
    MyApp,
    Login,
    QRCodeComponent
  ],
  imports: [
...
```

5. Finaly, use it in your HTML templates the same way as described in current repository.
```html
<qr-code [value]="value_variable" [size]="300"></qr-code>
```

Good luck!

**Comment by ruudboon** [comment]
Trying to solve this issue in a cloned repository. Not sure if it's really related to this project. Looks like it has something to do with the building process.

This works:
```
ng build --prod --aot=false
```

**Comment by Captnwalker1** [comment]
Switched to this fork, seems to be working: https://github.com/dapriett/angular2-qrcode

**Comment by SuperiorJT** [comment]
Closing this with the 2.0.1 release.

**Comment by nitinw631** [comment]
thanks for closing this issues..   @SuperiorJT  :)
