### ISSUE TITLE
latest ng2 - directives have depreciated

### ISSUE THREAD

**Issue by rrubio** [SuperiorJT/angular2-qrcode#14]
Hi Guys,

Since directives have been depreciated on the latest/stable angular2, is there a chance you could update your how to implement this library. Having troubles getting it to work.

Cheers :-)

**Comment by cedWetzel** [comment]
Don't add it as an directive in your component but follow the other instructions and you should be fine :)

**Comment by SuperiorJT** [comment]
I have updated the usage instructions to just have NgModule usage. Thanks for pointing this out!
