### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Blackscr33n** [SuperiorJT/angular2-qrcode#16]
Got this error while trying to install the npm-package:

![bildschirmfoto 2017-02-27 um 16 55 56](https://cloud.githubusercontent.com/assets/6410789/23368300/ab0e824e-fd0d-11e6-9474-5811e6cbfd7d.png)

**Comment by SuperiorJT** [comment]
Ignore this error for now. There currently is no way to set `--no-optional` in `package.json`.
