### ISSUE TITLE
ERROR in QRCodeModule is not an NgModule

### ISSUE THREAD

**Issue by d3vzr** [SuperiorJT/angular2-qrcode#18]
When I try ng build I face this error
ERROR in QRCodeModule is not an NgModule

my ng v
@angular/cli: 1.0.0-rc.0
node: 7.2.1
os: linux x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9

**Comment by jinceon** [comment]
same problem.
after I add `@NgModule()` in `angular2-qrcode.d.ts` [pr#9](https://github.com/SuperiorJT/angular2-qrcode/pull/9/commits/6aee5df766ae84185dfdcaf3d58d2037a5d21045), `ng build` runs well, but `ng build -prod` still don't.

Finally I copied `angular2-qrcode.ts` to my project component folder, and imported it in `declarations` of `app.module.ts`.

**Comment by d3vzr** [comment]
Can you give me more details about the second solution ?

**Comment by jinceon** [comment]
@geeksamu 
in some way, I steal @SuperiorJT 's code.
![image](https://cloud.githubusercontent.com/assets/1641265/23820363/a1933d0c-0651-11e7-9419-4d322b161650.png)

angular2-qrcode depends on `qrious`, so I use `qrious` directly.

1. `npm install --save qrious`
2.  download [angular2-qrcode.ts](https://github.com/SuperiorJT/angular2-qrcode/blob/master/angular2-qrcode.ts), and place it into my project.
3. update app.module.ts ,add `QRCodeComponent` in `declarations`.

```
import { QRCodeComponent } from './qrcode/qrcode.component'; 
@NgModule({
  imports: [], // don't need QRCodeModule any more
  declarations: [...., QRCodeComponent ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

**Comment by nijinaniyath** [comment]
@jinceon failed to  compile the line import * as Qrious from 'qrious' , and I could'n't find typing file for qrious..  Error says
ERROR in ./src/app/shared/qr-code/qr-code.ts
Module build failed: Error:/src/app/shared/qr-code/qr-code.ts (9,26): Cannot find module 'qrious'.)

Any idea ?

**Comment by thackerronak** [comment]
@nijinaniyath Have you got any solution?

**Comment by SuperiorJT** [comment]
Closing this with the 2.0.1 release.
