### ISSUE TITLE
Not work in aot

### ISSUE THREAD

**Issue by Alsmile** [SuperiorJT/angular2-qrcode#2]
Unexpected value 'QRCodeModule' imported by the module 'SharedModule'

It need *.metadata.json

**Comment by jafaripur** [comment]
Yes, same for me. not work with AoT compiler.

**Comment by gr8den** [comment]
I try solve, but can't.
My package.json. It make *.matadata.json, but fail ngc of project:

```
{
  "name": "angular2-qrcode",
  "version": "1.0.5",
  "description": "An Angular 2 component that generates a QR Code.",
  "main": "angular2-qrcode.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SuperiorJT/angular2-qrcode.git"
  },
  "scripts": {
    "prepublish": "node ./node_modules/@angular/compiler-cli/src/main.js"
  },
  "keywords": [
    "qrcode",
    "qr",
    "code",
    "angular2",
    "angular",
    "2",
    "ng2"
  ],
  "dependencies": {
    "qrcode-generator": "^1.0.0"
  },
  "peerDependencies": {
    "@angular/core": "2.0.1",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.17"
  },
  "devDependencies": {
    "es6-promise": "^3.2.1",
    "es6-shim": "^0.35.1",
    "typescript": "^2.0.3",
    "typings": "1.2.0",
    "@angular/core": "2.0.1",
    "@angular/compiler": "2.0.1",
    "@angular/compiler-cli": "^0.6.2",
    "rxjs": "5.0.0-beta.12"
  },
  "typings": "angular2-qrcode.d.ts",
  "author": "superiorjt <superiorjt@gmail.com>",
  "license": "MIT"
}
```

**Comment by stevengunneweg** [comment]
@gr8den Maybe this link can help you: https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.uafrtbce4

**Comment by stevengunneweg** [comment]
I tried it myself as well with your package.json and also get an error:

```
ngc error: can't resolve module /Users/.../node_modules/angular2-qrcode/angular2-qrcode.d.ts
ngc error: Error: Source file /Users/.../node_modules/angular2-qrcode/angular2-qrcode.ts not present in program.
```

Is this the same error you encountered? (the file does exist btw)

**Comment by gr8den** [comment]
@stevengunneweg yes, same problem. I solve it: copy angular2-qrcode.ts in my project and use it as other components, now angular2-qrcode.ts compile using project compiler

**Comment by stevengunneweg** [comment]
@gr8den thanks for the tip. I also created a similar workaround to get it to work, however this should only be a temporary fix in my opinion.

**Comment by speedfl** [comment]
Hello,
Quick question. I tried to copy in my project the file as you said. However I am getting an error at initialisation:  angular2-qrcode.ts:38 Could not generate QR Code: qrcode is not defined

I added the "qrcode-generator": "^1.0.7" in my package.json but style the issue

do you maybe have an idea?

**Comment by stevengunneweg** [comment]
Did you add it correctly in you `app.module.ts`?

**Comment by speedfl** [comment]
Yes of course. However I took code from the izee PR and now it is working perfectly.
In fact last version of angular do not like require and use only import blablabla from 'package'

**Comment by stevengunneweg** [comment]
So it seems you no longer have issues using the plugin?

**Comment by speedfl** [comment]
No it is ok I can use it however with workarounds. I copied the angular2-qrcode.ts from izee pull request locally in my project and declared it as import in my module. But as you said earlier it must be a temporary solution. The *.metadata.json must be solved I guess :) anyway thanks to gr8den for his solution :)

**Comment by SuperiorJT** [comment]
Closing this thanks to #4
