### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by christophedemey** [SuperiorJT/angular2-qrcode#36]
Hi 

When i install component i get error for a pyton component.
Dont know what to do, please help.

Thanks.
![pytonerror](https://user-images.githubusercontent.com/13153164/41810471-4232dc94-76ff-11e8-83f2-54e393fc5266.PNG)

**Comment by SuperiorJT** [comment]
This is part of the npm error that is thrown from trying to install unneeded optional dependencies. You can ignore this error.
