### ISSUE TITLE
MIT License but has GPL3 dependancy

### ISSUE THREAD

**Issue by needsmorecoffee** [SuperiorJT/angular2-qrcode#37]
I noticed during a license review of my app dependancies that even though angular2-qrcode is published under the MIT license, the QRious dependancy is licensed under GPL3. As far as I am aware, this means that angular2-qrcode should also have a GPL3 license.

I am not affiliated with the QRious project so this isn't me trying to be the license police. It is more the case that I would like to confirm that I am allowed use angular2-qrcode under MIT as it stands, or else if it is possible to remove the GPL dependancy.

**Comment by SuperiorJT** [comment]
You can use my code under MIT. So if you want to swap out qrious for another library, I would suggest forking this repo and making those changes to use the other qr library.
