### ISSUE TITLE
Can't bind to 'data' since it isn't a known property of 'qr-code'.

### ISSUE THREAD

**Issue by RaulGarafulic** [SuperiorJT/angular2-qrcode#5]
Hello, I'm getting this error on my template. 

`<qr-code [ERROR ->][data]="'All QR Code data goes here!'" [size]="150"></qr-code> `

Any ideas why?

I have to say that I'm developing in Ionic 2. I imported everything fine, but still have this error.

**Comment by delcerrocristian** [comment]
Hi! you should try [value] instead of [data] :)

**Comment by sid145** [comment]
@delcerrocristian How about when trying to bind data from the controller?

**Comment by appzone** [comment]
change to [value] also got same problem
refer to #12

**Comment by SuperiorJT** [comment]
Is there anybody still having issues with this?

**Comment by pcsantana** [comment]
I'm having the same issue even with [value] attribute. And during the instalation I had the same erro to [#16](https://github.com/SuperiorJT/angular2-qrcode/issues/16).
I'm using Angular 4 and Ionic 3, maybe this is the problem?

Thanks!

The console error:

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'qr-code'.
1. If 'qr-code' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'qr-code' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </div>
            <div>
                <qr-code [ERROR ->][value]="'All QR Code data goes here!'" [size]="150"></qr-code>
            </div>
        </ion-card"): ng:///HomeModule/HomeComponent.html@115:25
```

**Comment by SuperiorJT** [comment]
Do the other attributes work? Make sure that you have `QRCodeModule` listed in the imports of your app module. If that doesn't work, this may be a bug with Ionic. I haven't tried using this with Ionic before so maybe something isn't compatible with it.

**Comment by pcsantana** [comment]
Thanks for reply! I found the problem. I'm using [LazyLoading feature](http://blog.ionic.io/ionic-and-lazy-loading-pt-1/) of the Ionic 3. So, I have to import the `QRCodeModule` in my HomeModule (module of the HomeComponent) instead of AppModule. When I did it, everything worked great!

**Comment by franzisk** [comment]
Hey guys,

Any of you could use a variable from the class as the value of the qrcode?

Something like this:
`<qr-code [(value)]="myQrCodeId" [size]="200" [level]="H" ></qr-code>`

**Comment by Vinutha-BK** [comment]
@pcsantana 
It looks like you have not included QR module in 'module' class.
import { QRCodeModule } from 'angular2-qrcode';
imports: [
QRCodeModule]

**Comment by prarthitshah899** [comment]
> Thanks for reply! I found the problem. I'm using [LazyLoading feature](http://blog.ionic.io/ionic-and-lazy-loading-pt-1/) of the Ionic 3. So, I have to import the `QRCodeModule` in my HomeModule (module of the HomeComponent) instead of AppModule. When I did it, everything worked great!

how did you do that

**Comment by Crypt0Graphic** [comment]
> > Thanks for reply! I found the problem. I'm using [LazyLoading feature](http://blog.ionic.io/ionic-and-lazy-loading-pt-1/) of the Ionic 3. So, I have to import the `QRCodeModule` in my HomeModule (module of the HomeComponent) instead of AppModule. When I did it, everything worked great!
> 
> how did you do that

Just put it in your page's -lazy loading- module file:

`import { QRCodeModule } from 'angularx-qrcode';`

```
imports: [
...
   QRCodeModule
...
]
```

**Comment by SuperiorJT** [comment]
Looks like this issue is resolved. Closing :)
