### ISSUE TITLE
ERROR in QRCodeModule is not an NgModule

### ISSUE THREAD

**Issue by koinedevelopment** [SuperiorJT/angular2-qrcode#7]
Every time I serve my project or build it, I have this error message. This is stopping to build with AoT.

**Comment by kormic** [comment]
I have the same problem...using angular-cli: 1.0.0-beta.22-1

**Comment by SuperiorJT** [comment]
Currently, the way that the type definitions are made are through tsc generation. Does anybody know of a way to make that work with NgModule rather than having to manually add it to the type definitions when adding new features?

**Comment by SuperiorJT** [comment]
Closing this with the 2.0.1 release.

**Comment by danaERadwin** [comment]
I am using 2.0.1 release, and still dealing with this issue.
